### ISSUE TITLE
SteamVR closes at startup

### ISSUE THREAD

**Issue by pitboxx** [r57zone/OpenVR-ArduinoHMD#1]
I use DIY Arduino headtracker that produces the following data at 115200 BaudRate.

```
 float mypr[3] = {0, 0, 0}; //yaw, pitch, roll                 
            mypr[0] = ypr[0] * 180/M_PI;
            mypr[1] = ypr[1] * 180/M_PI;
            mypr[2] = ypr[2] * 180/M_PI;
           
            Serial.write((byte*) mypr, sizeof(mypr)); 
```
I've copied "arduinohmd" folder to SteamVR drivers folder, set COM port number in "arduinohmd" settings file. Then I've connected tracker via USB 2.0 and open SteamVR

SteamVR freezes and closes on startup every time.

The message from Windows Application log (I use OS Windows 10 ver. 20H2, OS build 19042.):

```
Faulting application name: vrstartup.exe, version: 1.18.7.0, time stamp: 0x60e61656
Faulting module name: ucrtbase.dll, version: 10.0.19041.789, time stamp: 0x82dc99a2
Exception code: 0xc0000409
Fault offset: 0x0009eddb
Faulting process id: 0x30a0
Faulting application start time: 0x01d783c1476f445d
Faulting application path: C:\Program Files (x86)\Steam\steamapps\common\SteamVR\bin\win32\vrstartup.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report Id: 36913a40-0d5f-4d17-be45-d42ebb7f07fc
Faulting package full name:
Faulting package-relative application ID:

```
My steamvr.vrsettings file is

```
{
   "DesktopUI" : {
      "pairing" : "568,271,800,600,0",
      "settings_desktop" : "624,432,800,600,0"
   },
   "dashboard" : {
      "enableDashboard" : false
   },
   "steamvr" : {
      "activateMultipleDrivers" : true,
      "allowAsyncReprojection" : false,
      "directMode" : false,
      "enableHomeApp" : false,
      "installID" : "13246197459664423944",
      "lastVersionNotice" : "1.18.7",
      "lastVersionNoticeDate" : "1626220647",
      "showMirrorView" : false,
      "startMonitorFromAppLaunch" : false
   }
}
```
Without connecting Arduino, SteamVR starts normally

SteamVR version:

Built Jul 8, 2021 at 07:05
Version 1.18.7 (1625702712)

**Comment by r57zone** [comment]
Hi, have you changed the screen resolution and window size in the config file to suit yours? Try also changing the debug parameter to true.

SteamVR starts up, do you mean the Headset Window starts up and shows a stereo image there?

**Comment by pitboxx** [comment]
Above all, I ran the driver without my DIY HMD screen, because I don't have access to it right now.
So I've not changed the resolution settings in default.vrsettings because it wasn't necessary.
So is it possible to run the driver without an additional screen?

My "arduinohmd" settings file looks as the following:

```
{
   "arduinohmd" : {
      "COMPort" : 8,
      "CenteringKey" : 101,
      "CrouchPressKey" : 111,
      "CrouchOffset" : 0.7
   },
   "steamvr" : {
      "DebugMode" : false,
      "Stereo" : true,
      "DistanceBetweenEyes" : 0,
      "DistortionK1" : 0.91,
      "DistortionK2" : 0.93,
      "ScreenOffsetX" : 0,
      "ZoomHeight" : 0.8,
      "ZoomWidth" : 0.8,
	  "FOV" : 57.296,
      "displayFrequency" : 60,
      "renderHeight" : 1080,
      "renderWidth" : 1080,
      "secondsFromVsyncToPhotons" : 0.004999999888241291,
      "serialNumber" : "1001",
      "windowHeight" : 1080,
      "windowWidth" : 1920,
      "windowX" : 0,
      "windowY" : 0
   }
}

```
Changing the debug parameter did not give visible results. What should have changed? 
The SteamVR window is not displayed at all at startup.

**Comment by r57zone** [comment]
What is your monitor resolution? 1920 by 1080?

**Comment by pitboxx** [comment]
I'm running on a laptop with a FullHD 1920x1080 screen.

**Comment by r57zone** [comment]
A new version has been released, you can check it out, maybe it works for you.
