### ISSUE TITLE
STM32 Version

### ISSUE THREAD

**Issue by AnthonyGithub** [r57zone/OpenVR-ArduinoHMD#3]
Hi, I have a question regarding this project. I am trying to adapt your code for Arduino to be used on an STM32 (STM32H750XB) board with MPU6050. 

Will this driver work as long as the STM32 board is communicating through USB COM with a baud rate of 115200? As I am writing my own code to transmit the signal to the PC, what should be the output from the STM32 to the PC?

**Comment by r57zone** [comment]
Hi, yes, it should work with any 115200 com port.
