### ISSUE TITLE
 Headset Window not showing

### ISSUE THREAD

**Issue by r57zone** [r57zone/OpenVR-ArduinoHMD#7]
Headset Window is no longer showing after the update SteamVR
https://github.com/ValveSoftware/openvr/issues/1780

As a temporary solution, you can use an old version of SteamVR.
1. Uninstall the current SteamVR.
2. [Unzip this file](https://github.com/r57zone/VR-tracking-apps/releases/download/1/SteamVR.1.18.31.07.21.7z) to C:\Program Files\SteamVR.
3. Run "vrstartup.exe".

**Comment by 7ep3s** [comment]
restarting the VRCompositor seems to help and the window won't vanish afterwards!

open windows powershell and paste this one-liner:
`get-process vrcompositor | stop-process -Force;cd "C:\Program Files (x86)\Steam\steamapps\common\SteamVR\bin\win64";.\vrcompositor.exe`

**Comment by r57zone** [comment]
The problem is fixed in beta 2.2.1  - https://store.steampowered.com/news/app/250820/view/3873722126474526180
